SET FOREIGN_KEY_CHECKS=0;

-- Users
DROP TABLE IF EXISTS Users;
Create TABLE Users(
  user_id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL
);

-- Quizzes
DROP TABLE IF EXISTS Quizzes;
CREATE TABLE Quizzes(
  quiz_id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  quiz_type VARCHAR(255) NOT NULL,
  created_at VARCHAR(255) NOT NULL,
  score VARCHAR(255) NOT NULL,
  user_id INT NOT NULL,
  FOREIGN KEY (user_id) REFERENCES Users(user_id)
    ON DELETE CASCADE
);

  -- Scales
DROP TABLE IF EXISTS Scales;
CREATE TABLE Scales(
  scale_id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  created_at VARCHAR(255) NOT NULL,
  user_id INT NOT NULL,
  FOREIGN KEY (user_id) REFERENCES Users(user_id)
    ON DELETE CASCADE
);

-- Notes
DROP TABLE IF EXISTS Notes;
CREATE TABLE Notes(
  note_id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  note VARCHAR(255) NOT NULL,
  priority INT NOT NULL,
  octave INT NOT NULL
);

-- Scales_Notes
DROP TABLE IF EXISTS Scales_Notes;
CREATE TABLE Scales_Notes(
  scale_id INT NOT NULL,
  note_id INT NOT NULL,
  FOREIGN KEY (scale_id) REFERENCES Scales(scale_id)
	ON DELETE CASCADE,
  FOREIGN KEY (note_id) REFERENCES Notes(note_id) 
);

SET FOREIGN_KEY_CHECKS=1;
